name: Publish to S3

on:
  push:
    branches: [ "main" ]



jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - run: npm install
      - run: npm run build

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ env.AWS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ env.AWS_BUCKET }}
          source_dir: 'build'