name: Publish to S3

on:
  push:
    branches: [ "main" ]



jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - run: npm install
      - run: npm run build

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-1

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync build s3://${{env.AWS_BUCKET}} --delete